name: myserve
volumes:
  db:
networks:
  default:
    name: myserve-network

services:
  devdb:
    container_name: devdb 
    image: postgres:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb 
    ports:
      - 54321:5432
