name: myserve

extra-source-files:
- README.md

dependencies:
- aeson
- base
- base58-bytestring
- base64-bytestring
- base32
- brick
- beam-core
- beam-postgres
- crypton
- bytestring
- http-client
- memory
- envy
- extra
- postgresql-simple
- postgresql-migration
- optparse-applicative
- resource-pool
- servant-server
- servant-client
- servant-client-core
- time
- warp
- containers
- wai
- text
- mtl
- network
- http-types
- case-insensitive
- uuid
- vty
- text-zipper
- microlens-th
- microlens
- vector
- time
- websockets
- serialise
- lens

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors

library:
  source-dirs: src

executables:
  speakeasy-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myserve

  speakeasy-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myserve