{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Crypto.DoubleRatchet.GenState
  ( MessageKeyId(..)
  , RatchetM
  , RatchetState(..)
  , ReceivingChainState(..)
  , SendingChainState(..)
  , advanceReceivingChain
  , advanceSendingChain
  , advanceSendingRatchet
  , initializeDoubleRatchet
  , runRatchetM
  , DoubleRatchetImplementation(..)
  )
where

import Data.List (unsnoc)
import Control.Lens (makeLenses, zoom, use, (.=), use, At (at), (+=), (%=))
import Data.Map.Strict qualified as Map
import Control.Monad.State (State, runState)
import Data.Set qualified as Set

-- | Typeclass for implementations of the double ratchet state machine defined in this module.
class DoubleRatchetImplementation impl where

  -- | Key for the root ratchet that spawns chain ratchets.
  type RootKey impl

  -- | Key for the chain ratchet that spawns message keys.
  type ChainKey impl

  -- | Keys that can be generated by the chain ratchet.
  type MessageKey impl

  -- | Secret key.
  type SecretKey impl

  -- | Public key.
  type PublicKey impl

  -- | Shared secret that can be derived using our 'SecretKey' and their 'PublicKey'.
  type SharedSecret impl

  -- | Our identity. This can be a user ID or any other long-term identifier.
  -- In your implementation, this can resolve to the same type as TheirId, but this class provides
  -- separate type families to help avoid any ambiguity.
  type OurId impl

  -- | Their identity. This can be a user ID for any other long-term identifer.
  -- In your implementation, this can resolve to the same type as OurId, but this class provides
  -- separate type families to help avoid any ambiguity.
  type TheirId impl

  -- | Derive the public key for a secret key.
  toPublicKey :: SecretKey impl -> PublicKey impl

  -- | Derive a shared secret from their public key and our secret key.
  deriveSharedSecret :: PublicKey impl -> SecretKey impl -> SharedSecret impl

  -- | Given the current chain ratchet key, derive the next key and get a new message key.
  deriveNextChainKey :: ChainKey impl -> (MessageKey impl, ChainKey impl)

  -- | Initialize the root ratchet and get sending and receiving chain keys.
  initializeRootRatchet
    :: OurId impl -> TheirId impl -> SharedSecret impl -> (RootKey impl, ChainKey impl, ChainKey impl)

  -- | Give the current root ratchet key, derive the next key and get a new sending chain ratchet key.
  deriveNextRootKeySending
    :: RootKey impl -> OurId impl -> TheirId impl -> SharedSecret impl -> (RootKey impl, ChainKey impl)

  -- | Give the current root ratchet key, derive the next key and get a new receiving chain ratchet key.
  deriveNextRootKeyReceiving
    :: RootKey impl -> OurId impl -> TheirId impl -> SharedSecret impl -> (RootKey impl, ChainKey impl)

data SendingChainState impl = SendingChainState
  { _sendingChainKey :: ChainKey impl
  , _nextSendingMessageIndex :: Int
  , _previousSendingChainLength :: Int
  }

makeLenses ''SendingChainState

data ReceivingChainState impl = ReceivingChainState
  { _receivingChainKey :: ChainKey impl
  , _receivingChainEpoch :: PublicKey impl
  , _knownReceivingChainEpochs :: Set.Set (PublicKey impl)
  , _nextReceivingMessageIndex :: Int
  , _skippedMessageMap :: Map.Map (PublicKey impl, Int) (MessageKey impl)
  }

makeLenses ''ReceivingChainState

data RatchetState impl = RatchetState
  { _root :: RootKey impl
  , _dhSecretKey :: SecretKey impl
  , _sendingChainState :: SendingChainState impl
  , _receivingChainState :: ReceivingChainState impl
  }

makeLenses ''RatchetState

-- | Initialize a double ratchet.
initializeDoubleRatchet
  :: forall impl. DoubleRatchetImplementation impl
 -- ^ Cryptographic primitives that drive the state machine
  => PublicKey impl
 -- ^ The other party's public key
  -> SecretKey impl
 -- ^ Our secret key
  -> OurId impl
 -- ^ Our identity
  -> TheirId impl
 -- ^ Their identity
  -> RatchetState impl
initializeDoubleRatchet dhPublicKey' dhSecretKey' ourUserId theirUserId =
  let derivedSecret = deriveSharedSecret @impl dhPublicKey' dhSecretKey'
      (rootKey', sendingChainKey', receivingChainKey') =
        initializeRootRatchet @impl ourUserId theirUserId derivedSecret
  in  initializeRatchetState dhPublicKey' sendingChainKey' receivingChainKey' rootKey'
 where
  initializeRatchetState receivingChainEpoch' sendingChainKey' receivingChainKey' rootKey' =
    RatchetState
      { _root = rootKey'
      , _dhSecretKey = dhSecretKey'
      , _sendingChainState =
          SendingChainState
            { _sendingChainKey = sendingChainKey'
            , _nextSendingMessageIndex = 0
            , _previousSendingChainLength = 0
            }
      , _receivingChainState =
          ReceivingChainState
            { _receivingChainEpoch = receivingChainEpoch'
            , _knownReceivingChainEpochs = Set.singleton dhPublicKey'
            , _receivingChainKey = receivingChainKey'
            , _nextReceivingMessageIndex = 0
            , _skippedMessageMap = Map.empty
            }
      }

type RatchetM impl = State (RatchetState impl)

runRatchetM :: forall impl a. RatchetState impl -> RatchetM impl a -> (a, RatchetState impl)
runRatchetM = flip runState

data MessageKeyId dhPublicKey = MessageKeyId
  { keyIndex :: Int
  , chainEpoch :: dhPublicKey
  } deriving (Eq, Ord, Show)

advanceSendingChain
  :: forall impl. DoubleRatchetImplementation impl
  => RatchetM impl (MessageKeyId (PublicKey impl), (MessageKey impl), Int)
advanceSendingChain = do
  (messageKey, keyIndex) <- zoom sendingChainState $ do
      chainKey <- use sendingChainKey
      chainIndex <- use nextSendingMessageIndex
      let (messageKey, nextChainKey) = deriveNextChainKey @impl chainKey
      sendingChainKey .= nextChainKey
      nextSendingMessageIndex += 1
      pure (messageKey, chainIndex)
  dhSecretKey' <- use dhSecretKey
  previousSendingChainLength' <- use (sendingChainState . previousSendingChainLength)
  pure
    ( MessageKeyId
        { chainEpoch = toPublicKey @impl dhSecretKey'
        , ..
        }
    , messageKey
    , previousSendingChainLength'
    )

-- | Advance the receiving message chain by a single step
singleAdvanceReceivingChain
  :: forall impl. DoubleRatchetImplementation impl
  => RatchetM impl (MessageKey impl) 
singleAdvanceReceivingChain = zoom receivingChainState $ do
  chainKey <- use receivingChainKey
  let (messageKey, nextChainKey) = deriveNextChainKey @impl chainKey
  receivingChainKey .= nextChainKey
  nextReceivingMessageIndex += 1
  pure messageKey

advanceReceivingChain
  :: forall impl. (DoubleRatchetImplementation impl, Ord (PublicKey impl))
  => MessageKeyId (PublicKey impl) 
  -> Int
  -- ^ Previous chain length
  -> OurId impl 
  -> TheirId impl
  -> RatchetM impl (Maybe (MessageKey impl))
advanceReceivingChain messageKeyId previousChainLength ourUserId theirUserId = do

  currentReceivingChainEpoch <- use (receivingChainState . receivingChainEpoch)
  knownReceivingChainEpochs' <- use (receivingChainState . knownReceivingChainEpochs)

  -- Requesting a key in the same chain epoch as our receiving chain state
  if chainEpoch messageKeyId == currentReceivingChainEpoch
    then currentEpochLookup

  -- Requesting a key in an older chain epoch
  else if chainEpoch messageKeyId `Set.member` knownReceivingChainEpochs'
    then do
      -- Since it's an older epoch, we go straight to the skipped message cache
      skippedMessageMap' <- use (receivingChainState . skippedMessageMap)
      let messageKeyMaybe =
            Map.lookup (chainEpoch messageKeyId, keyIndex messageKeyId) skippedMessageMap'
      receivingChainState . skippedMessageMap . at (chainEpoch messageKeyId, (keyIndex messageKeyId)) .= Nothing
      -- If we can't find a message key, it must have already been consumed... or we got a bogus message key ID
      -- Either way, we don't care
      pure messageKeyMaybe

  -- Requesting a key in a new epoch
  else do
    -- Update the set of known epochs
    receivingChainState . knownReceivingChainEpochs %= Set.insert (chainEpoch messageKeyId)
    -- Advance ratchet and get a new sending chain key
    advanceReceivingRatchet (chainEpoch messageKeyId) previousChainLength ourUserId theirUserId
    -- Now that we are in the correct epoch, we can do a current-epoch lookup
    currentEpochLookup

 where
  currentEpochLookup :: RatchetM impl (Maybe (MessageKey impl))
  currentEpochLookup = do
    nextReceivingIndex <- use (receivingChainState . nextReceivingMessageIndex)
    if (keyIndex messageKeyId) == nextReceivingIndex
      then fmap Just singleAdvanceReceivingChain
    else if (keyIndex messageKeyId) > nextReceivingIndex
      then do
        zoom receivingChainState $ do
          chainKey <- use receivingChainKey
          oldMissedMessageMap <- use skippedMessageMap
          latestReceivingChainEpoch <- use receivingChainEpoch
          let (skippedMessageKeys, newChainKey) =
                advanceFromTo @impl
                  nextReceivingIndex
                  (keyIndex messageKeyId) 
                  chainKey
          let newSkippedMessageMapEntries =
                Map.fromList $
                  fmap
                    (\(missedMessageKey, index) -> ((latestReceivingChainEpoch, index), missedMessageKey))
                    skippedMessageKeys
              newSkippedMessageMap = Map.union oldMissedMessageMap newSkippedMessageMapEntries
          skippedMessageMap .= newSkippedMessageMap
          receivingChainKey .= newChainKey
          nextReceivingMessageIndex .= (keyIndex messageKeyId) 
        fmap Just singleAdvanceReceivingChain
    else zoom receivingChainState $ do 
      latestReceivingChainEpoch <- use receivingChainEpoch
      skippedMessageMap' <- use skippedMessageMap
      let messageKeyMaybe =
            Map.lookup (latestReceivingChainEpoch, (keyIndex messageKeyId)) skippedMessageMap'
      skippedMessageMap . at (latestReceivingChainEpoch, (keyIndex messageKeyId)) .= Nothing
      pure messageKeyMaybe

advanceSendingRatchet
  :: forall impl. DoubleRatchetImplementation impl
  => SecretKey impl 
  -- ^ *Our* new secret key
  -> OurId impl
  -> TheirId impl
  -> RatchetM impl ()
advanceSendingRatchet newSecretKey ourUserId theirUserId = do
  oldRootKey <- use root
  previousSendingChainLength' <- use (sendingChainState . nextSendingMessageIndex)
  dhPublicKey' <- use (receivingChainState . receivingChainEpoch)
  let newDhSecret = deriveSharedSecret @impl dhPublicKey' newSecretKey
      (newRootKey, newSendingChainKey) =
        deriveNextRootKeySending
          @impl
          oldRootKey
          ourUserId
          theirUserId
          newDhSecret
  zoom sendingChainState $ do
    nextSendingMessageIndex .= 0
    sendingChainKey .= newSendingChainKey
    previousSendingChainLength .= previousSendingChainLength' 
  root .= newRootKey
  dhSecretKey .= newSecretKey

advanceReceivingRatchet
  :: forall impl. (DoubleRatchetImplementation impl, Ord (PublicKey impl))
  => PublicKey impl 
  -- ^ DH public key
  -> Int
  -- ^ Previous chain length
  -> OurId impl
  -> TheirId impl
  -> RatchetM impl ()
advanceReceivingRatchet dhPubKey previousChainLength ourUserId theirUserId = do
  -- Cache any skipped message keys if we're behind the sender
  zoom receivingChainState $ do
    chainIndex <- use nextReceivingMessageIndex
    chainKey <- use receivingChainKey
    oldMissedMessageMap <- use skippedMessageMap
    oldReceivingChainEpoch <- use receivingChainEpoch
    -- We discard the chain key as we'll get a new one from the advanced root
    let (skippedMessageKeys, _) = advanceFromTo @impl chainIndex previousChainLength chainKey
    let newSkippedMessageMapEntries =
          Map.fromList $
            fmap
              (\(missedMessageKey, index) -> ((oldReceivingChainEpoch, index), missedMessageKey))
              skippedMessageKeys
        newSkippedMessageMap = Map.union oldMissedMessageMap newSkippedMessageMapEntries
    skippedMessageMap .= newSkippedMessageMap
  oldRootKey <- use root
  dhSecretKey' <- use dhSecretKey
  let newDhSecret =  deriveSharedSecret @impl dhPubKey dhSecretKey'
      (newRootKey, newReceivingChainKey) =
        deriveNextRootKeyReceiving
          @impl
          oldRootKey
          ourUserId
          theirUserId
          newDhSecret
  root .= newRootKey
  zoom receivingChainState $ do
    nextReceivingMessageIndex .= 0
    receivingChainKey .= newReceivingChainKey
    receivingChainEpoch .= dhPubKey

advanceFromTo
  :: forall impl. DoubleRatchetImplementation impl
  => Int
  -> Int
  -> ChainKey impl
  -> ([(MessageKey impl, Int)], ChainKey impl)
advanceFromTo from to chainKey = do
  let go _ 0 = []
      go ck num =
        let (mk, nCk) = deriveNextChainKey @impl ck
        in (mk, nCk):(go nCk (num - 1))
  if from == to
    then ([], chainKey) -- no need to advance
  else if from > to
    then ([], chainKey) -- we got ahead with processing
  else
    -- do the advance
    let newKeys = go chainKey (to - from)
    in  case (fmap snd $ unsnoc newKeys) of
          Nothing -> ([], chainKey)
          Just (_, finalChainKey) -> (zip (fmap fst newKeys) [from ..], finalChainKey)